spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  datasource:
    generate-unique-name: false
    name: tacocloud
    username: sa
    password: password
    url: jdbc:h2:file:C:/Users/duffy/tacocloud
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          <oauth2 or openid provider name>:
            clientId: <google client id>
            clientSecret: <google client secret>
            scope: <comma-separated list of requested scopes>

